# This file was generated by GoReleaser. DO NOT EDIT.
cask "chaosproxy" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/chaosproxy"]
    end
  end

  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "4e1bc79ed2c87318cd9eb6c88313c7ddd29558b3195d41966c425870886ad4dd"
      url "https://github.com/Raxuis/ChaosProxy/releases/download/v#{version}/chaosproxy_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1eba43135fe51471cc65f5a7e7412746cb68db97439380c5ccd75eae1cd30eed"
      url "https://github.com/Raxuis/ChaosProxy/releases/download/v#{version}/chaosproxy_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a4572a239fe76a56bc0e6b775e04f33c27da1dc9263fed8535fa73b41700ce47"
      url "https://github.com/Raxuis/ChaosProxy/releases/download/v#{version}/chaosproxy_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a2f8f7ce631ec6ba2f54573c6c54ffd8f8f8e9046dec56043254c66b69e60150"
      url "https://github.com/Raxuis/ChaosProxy/releases/download/v#{version}/chaosproxy_#{version}_linux_amd64.tar.gz"
    end
  end

  name "chaosproxy"
  desc "HTTP-aware chaos proxy for frontend developers"
  homepage "https://github.com/Raxuis/ChaosProxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chaosproxy"

  # No zap stanza required
end
