# This file was generated by GoReleaser. DO NOT EDIT.
cask "chaosproxy" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "fb0e911adb43e8fbe2c44defc459e3fbbcef1a0d2d82ec6ff431ff92c86b2861"
      url "https://github.com/Raxuis/ChaosProxy/releases/download/v#{version}/chaosproxy_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cafb8dfe7fde7f527709e5501af686f3c7af00f7248418595864e643668f6cd1"
      url "https://github.com/Raxuis/ChaosProxy/releases/download/v#{version}/chaosproxy_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0e67d6bfcee7e75a0bb8690da27596bac9555e7a64390f1ded0fc9ae1355cff0"
      url "https://github.com/Raxuis/ChaosProxy/releases/download/v#{version}/chaosproxy_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a2817569b9f994b788d3eb90b14c8426f9e34e1b46762a3432f12f52dca53c2e"
      url "https://github.com/Raxuis/ChaosProxy/releases/download/v#{version}/chaosproxy_#{version}_linux_amd64.tar.gz"
    end
  end

  name "chaosproxy"
  desc "HTTP-aware chaos proxy for frontend developers"
  homepage "https://github.com/Raxuis/ChaosProxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chaosproxy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chaosproxy"]
    end
  end

  # No zap stanza required
end
