# This file was generated by GoReleaser. DO NOT EDIT.
cask "chaosproxy" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/chaosproxy"]
    end
  end

  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "178e4d30e60580377c867d6c079d9ac5b61fcfc3be6050b493e2e731cd48cfbb"
      url "https://github.com/Raxuis/ChaosProxy/releases/download/v#{version}/chaosproxy_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3f6c5df871fa0caa5c3dc4d9e3644fa7c70d0e94d2016fb82dae7e109c2a0daa"
      url "https://github.com/Raxuis/ChaosProxy/releases/download/v#{version}/chaosproxy_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "acc5e4e1d40ceba679e13e0d93601c97cf438b0c2d52289a7b15e10f79935277"
      url "https://github.com/Raxuis/ChaosProxy/releases/download/v#{version}/chaosproxy_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0c35c15b2a7a8bc2572ac4da2da226cccb9a071316d29ab4ddc41701724d3c59"
      url "https://github.com/Raxuis/ChaosProxy/releases/download/v#{version}/chaosproxy_#{version}_linux_amd64.tar.gz"
    end
  end

  name "chaosproxy"
  desc "HTTP-aware chaos proxy for frontend developers"
  homepage "https://github.com/Raxuis/ChaosProxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chaosproxy"

  # No zap stanza required
end
