# This file was generated by GoReleaser. DO NOT EDIT.
cask "raxuiscli" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "2fdf6c7b61236df39854448a34d7fba014b6d984c2cd893914fa1cd8fa9f2318"
      url "https://github.com/Raxuis/RaxuisCLI/releases/download/v#{version}/raxuiscli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8d4f24e305327e5720e3e9e6ece2cb8ba8d1447e98bf1c20a7d793757235cd63"
      url "https://github.com/Raxuis/RaxuisCLI/releases/download/v#{version}/raxuiscli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "945fdfc9774bdcd6abd10e5790e1b77cd4bdffa5d596acc16dfc21e0e17c853c"
      url "https://github.com/Raxuis/RaxuisCLI/releases/download/v#{version}/raxuiscli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "acb49e519e35a53a050142ed798ea97926637e478708358f123e0a2d0ce64b47"
      url "https://github.com/Raxuis/RaxuisCLI/releases/download/v#{version}/raxuiscli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "raxuiscli"
  desc "Cybersecurity CLI toolkit for pentest, CTF and security analysis"
  homepage "https://github.com/Raxuis/RaxuisCLI"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "raxuiscli"
  bash_completion "completions/raxuiscli.bash"
  fish_completion "completions/raxuiscli.fish"
  zsh_completion "completions/raxuiscli.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/raxuiscli"]
    end
  end

  # No zap stanza required
end
