# This file was generated by GoReleaser. DO NOT EDIT.
cask "raxuiscli" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "f9bcb3b37203fbdbb802c0cbb976ab8e5657a7ff60f35c397a9b3dcfb0c7b8cf"
      url "https://github.com/Raxuis/RaxuisCLI/releases/download/v#{version}/raxuiscli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8805c03517ae7fca43e76503316408ce0d361911211cbafd9cb6656d17be0953"
      url "https://github.com/Raxuis/RaxuisCLI/releases/download/v#{version}/raxuiscli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "334ca532c17d3bb75918b579f4b96887c844f7acb8eb2e6ad06e7f8b1294e263"
      url "https://github.com/Raxuis/RaxuisCLI/releases/download/v#{version}/raxuiscli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "17e23935387a4cc67104fe962e3be4273518eea9fb2c541515899bea5d9d926d"
      url "https://github.com/Raxuis/RaxuisCLI/releases/download/v#{version}/raxuiscli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "raxuiscli"
  desc "Cybersecurity CLI toolkit for pentest, CTF and security analysis"
  homepage "https://github.com/Raxuis/RaxuisCLI"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "raxuiscli"
  bash_completion "completions/raxuiscli.bash"
  fish_completion "completions/raxuiscli.fish"
  zsh_completion "completions/raxuiscli.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/raxuiscli"]
    end
  end

  # No zap stanza required
end
