# This file was generated by GoReleaser. DO NOT EDIT.
cask "raxuiscli" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "b9f206bfa141c4d71c7df83c59e66c97b0675e38ba0a0dd4c44d347c778558a0"
      url "https://github.com/Raxuis/RaxuisCLI/releases/download/v#{version}/raxuiscli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9a3e95cf54baa15c1a8da06b30d29d733ba1e898941f5604eae5fdb9a2fad719"
      url "https://github.com/Raxuis/RaxuisCLI/releases/download/v#{version}/raxuiscli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "dce36b2f1f2a153423a94fa883e29a1e024ce7d9b79c321f07c3393da0bca198"
      url "https://github.com/Raxuis/RaxuisCLI/releases/download/v#{version}/raxuiscli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "12323ec8d20289b43ee953af5a9ae8b75ef665192f3a2fec213500596778769e"
      url "https://github.com/Raxuis/RaxuisCLI/releases/download/v#{version}/raxuiscli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "raxuiscli"
  desc "Cybersecurity CLI toolkit for pentest, CTF and security analysis"
  homepage "https://github.com/Raxuis/RaxuisCLI"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "raxuiscli"
  bash_completion "completions/raxuiscli.bash"
  fish_completion "completions/raxuiscli.fish"
  zsh_completion "completions/raxuiscli.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/raxuiscli"]
    end
  end

  # No zap stanza required
end
